apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue

spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue

  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: blue
        
    spec:
      containers:
      - image: docker.io/davedecay/color-coded:{{CF_REVISION}}
        imagePullPolicy: Always
        name: blue
        # env:
        # - name: COLOR
        #   value: '#44B3C2'
        ports:
        - containerPort: 8080
          protocol: TCP

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
